# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alexs29
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: apisls
# "service" is the name of this project. This will also be added to your AWS resource names.
service: apisls

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt ProductsTable.Arn

plugins:
  - serverless-offline
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createProduct:
    handler: src/functions/createProduct.handler
    events:
      - httpApi:
          path: /product
          method: POST
  listProducts:
    handler: src/functions/listProducts.handler
    events:
      - httpApi:
          path: /products
          method: GET
deleteProduct:
  handler: src/functions/deleteProduct.handler
  events:
    - httpApi:
        path: /products/{productId}
        method: DELETE
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
